### ISSUE TITLE
over-large transaction when database wiped

### ISSUE THREAD

**Issue by xloem** [monkeylord/bsvup#1]
I lost my .bsv folder and regenerated it using my private key.

Unfortunately, my next upload dies with this:
```
Start Broadcasting, it may take a while and several block confirmation...
d59186c210ad88f5f427e49fce8b34230d07b5eecf3f35a86b421b5232508bbd 广播失败，原因 fail to broadcast:
the transaction was rejected by network rules.
64: tx-size
```

**Comment by monkeylord** [comment]
OK, I think I know the reason.
There are a lot of files needed to be uploaded/remaped in a brand-new uploading.
So there will be a lot of utxo requirement to fund those tasks, so the map TX (split original UTXO into chunks) become too big.
The code should estimate the size and handle utxos in multiple map TXs.

Let's see how to estimate the size.
This will be fixed.

**Comment by monkeylord** [comment]
Fixed.
Now it should use multiple map TXs, instead of a extremely large one.
