### ISSUE TITLE
New errors checking bitdb for file presence

### ISSUE THREAD

**Issue by xloem** [monkeylord/bsvup#17]
```
 - Checking get.sh        
3e92c8a80bf31be5b1b83e52879d66098c2a4440
 - 向BitDB搜索已存在的文件记录 Querying BitDB
 - TX Data not properly resolved. Error: Error: Not Data TX
 - TX Data not properly resolved. Error: Error: Not Data TX
 - TX Data not properly resolved. Error: Error: Not Data TX
 - TX Data not properly resolved. Error: Error: Not Data TX
 - TX Data not properly resolved. Error: Error: Not Data TX
 - TX Data not properly resolved. Error: Error: Not Data TX
 - TX Data not properly resolved. Error: Error: Not Data TX
 - TX Data not properly resolved. Error: Error: Not Data TX
 - TX Data not properly resolved. Error: Error: Not Matched
```

**Comment by monkeylord** [comment]
I think it's because bitindex free tier api, that bsvup cannot fetch tx data from bitindex.
Maybe sometimes insight api is more reliable.

**Comment by xloem** [comment]
It seems it would be better to use bitdb for such queries, to avoid that.  That's what I did with findTX earlier.  I'm not familiar with the current existence checking code, so I'm using an older version for now that doesn't show this issue.

**Comment by xloem** [comment]
I'm debugging this locally.  Looks like it's because `getData` is using `isDataOut` instead of `isSafeDataOut`.  PR likely will follow.

**Comment by xloem** [comment]
To clarify and confirm, these errors were because of problems with #16, which I authored and #18 fixes.  The new messages are revealing what I left out.

**Comment by monkeylord** [comment]
Ops, of cause.
getData should be upgraded, too.
