### ISSUE TITLE
Files lost when unconfirmed transactions not included in next block

### ISSUE THREAD

**Issue by xloem** [monkeylord/bsvup#27]
This obviously happens more when fees are reduced.

I tend to get confused from frustration when this happens, so a fix I submit may be kinda messy, but I'll likely try to make one to resolve my local uploads.

I'm thinking of adding a command that verifies transactions in tx/ are on the network and resends them if they aren't.

I'm thinking of changing the verification step, maybe to not remove transactions until they are confirmed, by making more queries or sending redundant broadcasts.

**Comment by monkeylord** [comment]
Maybe the priority of TXs with reduced fee are low, so they may be lost on remote node during relaying.
Waiting for confirmation may be needed, as peer network had never promise 100% delivery.

**Comment by xloem** [comment]
Resolved for me with #28
