### ISSUE TITLE
findExist: gateway timeout

### ISSUE THREAD

**Issue by fuzzyTew** [monkeylord/bsvup#7]
I sometimes get this repeatedly while bsvup is checking if a file exists:
```
获取TX时发生错误 Error acquring TX                                                                                    
<html>                                                                                                               
<head><title>504 Gateway Time-out</title></head>                                                                      
<body bgcolor="white">                                                                                                
<center><h1>504 Gateway Time-out</h1></center>                                                                        
</body>                                                                                                               
</html>                                                                                                               
```

I'm worried it may be falsely deciding the file does not exist when it does.  Would it make sense to wait 1 second on a 504 and try again?

**Comment by monkeylord** [comment]
Insight API is not 100% reliable.
So I use cache, that once the tx is found, it will not be download again.
You can abandon broadcast and try again. Those already downloaded TXs will not be downloaded, so it's quick.

However, I will add some retries.

**Comment by fuzzyTew** [comment]
I guess really this just shows we need to be able to use local services.  It sounds like if the upload is made on the same computer, it will find the tx in the cache and all will be well.
